[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/"
  to = "/meustudio.html"
  status = 200

[[redirects]]
  from = "/guest"
  to = "/guest.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache, no-store, must-revalidate"
